version: 0.0
os: linux
files: 
  - source: /
    destination: /var/www/whitecoatdomain
file_exists_behavior: RETAIN
hooks:
  ApplicationStop:
    - location: CICDScripts/application_stop.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: CICDScripts/before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: CICDScripts/application_start.sh
      timeout: 300
      runas: ubuntu